language: node_js
node_js:
- iojs
- '7'
deploy:
  provider: heroku
  app: frozen-atoll-71800
  api_key:
    secure: NZ+8I3qc47VC1tFgfnuPm+AOpaUGie7KGJUx7PchAaxqmhtlIlk5iXhuHlsQeyO/F9bax3YeFECXb8TtfDglOEyOqPompH9UTgm/EWQPOnpmjpht4vOjknBfxJB5HzmykCoghSCROK23KoWp6B4q8P46u88qYZ1ilaMbr5sxGux3ZcW59E//zc0pJl0DZOaVuUdIHbzjGbpftQhRsyLY6wz8d23yUPMT3/rQi/ixDR0mc7UMVMPtbgRHwAWheOmBuMhvCBr9gaP4AdcEvK4FLshL1I0g6GEzE8Zv4a+r5vVFW3l0MKMfDLav9km52QG8ONzgXhpDVktKSCloTFkZll2Lzh3kfCxU0YoiPH49nnh13ytb9ZX3PHSeGh69UEseaeSyUv21+rooNSlJ1XkI1MJ4UKRNQeH2bN90dJfkPucb0z8vZhf1SXM9RjamIv/0qF+B/bA9f2xwKBqA5/BvYTQ26GM6gJygy6CMogCtOts2H0ehKweI8ty2cipxmrTSlIFZ2qHDbz3lRq02XTJsMSYIRgXcms4iTkcjr1ucAPKWyjRP7zl1ce7t8E7Se3x0dbNz9lbL6Il+t9kDMY5UQoCoRI1OShAqAeWzuYresnRQJkOGzichSmaRHgjD06xuZAOgl/QOOm3IUyf0hKQUmBIGX2QX5xgro8cfZqSxjC4=
