language: node_js
node_js:
- iojs
- '7'
deploy:
  provider: heroku
  api_key:
    secure: n8rU/vPUrdYiLOBdn4j1vMLVn051fkjjqMMuovQWRS4Q0Vw2XQElR7X35HblvwO9PmDVUpZbVI2xEFSBzx1dvarMKOOtlT25Ht5m9mTYe0NdrmYi7UGh8m9b7Us+UEHxcY57mO4rlTd+aID/1jX1x2t+DiH0330qJXle1p7Sv8nyrIjNRrLWkfnly41bm/brSWEPjlnNSJ175an/Ya8fsUu3ymenBheX99051LtwOuKJ+kCCljK30kTSpIwyDEEDcwzqg6+6NHevNATZVzs0dKGcc3ekp51r7xl78H2BnuD7NHkQt1xO0/gwWBRV6x+NJP9aQf2DZrrY/IQwUb1OhDCvv0uP+gvP22W4J9fHbJ2DN+S3y4lah/CGQydMq3xh5W5eLTZDZk9uKsTuGvayfaChIxc27hs+kxs5WAwp5Ozd+WwUftmHVHWpXtZrgBPBvFXVehdy987NvoONTta6KuzcKlbNsygVC0sLAuyzGac9JcuGz9QQ1VDypfkfVtdiZtb4L021JkiSJIbUFVGcJ70fFESD+bMp598OAgny8Y3zWfwLrBkV5qb3TQd6SKSwdJILHaDk7CNa4reAXxUHj3blSnQvEvhL+zJwreatEMoORMTif3AmM53FmUE+iRXfzDT15sKGTXhgSFq355VSi6RntoH/Da75tE3FxwAqPLM=
